apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: java-4624
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-4624 
  name: java-4624
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: java-4624 
